<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>netstandard2.0</TargetFrameworks>
        <Description>Additional components for managing Azure Identity.</Description>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Azure.Core" Version="1.47.3" />
        <PackageReference Include="Azure.Identity" Version="1.15.0" />
        <PackageReference Include="Cogito.Extensions.Options.Configuration" Version="4.0.0" />
    </ItemGroup>

</Project>
